import fs from 'node:fs';
import { execSync } from 'node:child_process';

// 1. Read version from package.json
const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf-8'));
let version = pkg.version;

// 2. Append -unstable if requested
const isUnstable = process.env.IS_UNSTABLE === 'true';
if (isUnstable) {
  try {
    const commitHash = execSync('git rev-parse --short HEAD').toString().trim();
    version += `-unstable.${commitHash}`;
  } catch (e) {
    console.warn('Failed to get git commit hash, falling back to timestamp');
    version += `-unstable.${Date.now()}`;
  }
}

console.log(`Building version: ${version} (${isUnstable ? 'unstable' : 'stable'})`);

// 3. Run Vite build
// Pass version and unstable flag to Vite via environment variables
execSync('npx vite build', {
  stdio: 'inherit',
  env: {
    ...process.env,
    VITE_APP_VERSION: version,
    VITE_IS_UNSTABLE: String(isUnstable)
  }
});

// 4. Update version in header.ts and concatenate
let header = fs.readFileSync('./src/header.ts', 'utf-8');
header = header.replace(/@version\s+.*/, `@version         ${version}`);

if (isUnstable) {
  // Replace URLs pointing to stable branch with unstable branch
  // Only target lines starting with @updateURL or @downloadURL
  header = header.replace(/(\/\/\s*@(?:update|download)URL\s+.*\/)stable(\/.*)/g, '$1unstable$2');
}

// Warning message for the generated file
const warning = `/**
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 * This file is automatically generated by the build process.
 * Please edit files in the \`src/\` directory instead and run \`npm run build\`.
 */
`;

const bundle = fs.readFileSync('./dist/demaecan-no-ghosts.user.js', 'utf-8');
fs.writeFileSync('./dist/demaecan-no-ghosts.user.js', header + '\n' + warning + bundle);

console.log(`✅ Build complete: dist/demaecan-no-ghosts.user.js`);
